Package: expat
Version: 1.9.5
Revision: 9
Maintainer: Marmalade Package Team <packages@ideaworkslabs.com>
Mkbs: expat.mkf
Libraries: expat
Description: |
 XML parsing C library - runtime library.
 This package contains the runtime, shared library of expat, the C
 library for parsing XML. Expat is a stream-oriented parser in
 which an application registers handlers for things the parser
 might find in the XML document (like start tags).
Contents-Source:
 - README.rst
 - expat.defines.txt
 - expat_config.h
 - expat.mkf
Contents:
 - expat_config.h: h/expat_config.h
 - upstream/lib/expat_external.h: h/expat_external.h
 - upstream/lib/expat.h: h/expat.h
